### ISSUE TITLE
main.py just crashes when opened 

### ISSUE THREAD

**Issue by Eviltwin001** [jackssrt/robloxnotif#1]
When I open it, it opens for a second then just crashes. 
I have installed the requirements.txt file with the command given.
Here is what my jsonc file looks like from the outside: https://imgur.com/a/8xM9zY9
From the inside: https://imgur.com/a/VEQ2QHo
my whole folder: https://imgur.com/a/ktfxgkJ

**Comment by jackssrt** [comment]
Can you send a screenshot of running main.py from the command line / powershell / terminal? Like this 
![image](https://user-images.githubusercontent.com/33695699/128319086-f6a81433-49da-4c1e-b21c-f8453e659f08.png)

**Comment by Eviltwin001** [comment]
Hello, starting it from cmd somehow fixes it and it works perfectly, thanks for the help!
