### ISSUE TITLE
Sound Error

### ISSUE THREAD

**Issue by StevenRafft** [jackssrt/robloxnotif#2]
Hey there, I tried to use your application but, whenever a sound tries to get played it gives me this error
```
Error 259 for command:
    play ./sounds/robloxnotif.wav wait
The driver cannot recognize the specified command parameter.
[00:53:51]: [ERROR] Robloxnotif has errored:
Error: PlaysoundException
    Error 259 for command:
        play ./sounds/robloxnotif.wav wait
    The driver cannot recognize the specified command parameter.
Message: Unexpected error, Can't continue running.
Check error.log for a traceback.
Exception in thread
    Error 263 for command:
        open ./sounds/error.wav
    The specified device is not open or is not recognized by MCI.

Error 263 for command
    close ./sounds/error.wav
The specified device is not open or is not recognized by MCI.
Thread-2Failed to close the file: ./sounds/error.wav
```
I will try changing the .wav files to .mp3 files and see if that fixes it

**Comment by StevenRafft** [comment]
I have changed the .wave files to .mp3 files online, downloaded them, changed the code to make it use .mp3 instead of .wav, Still doesn't work.

**Comment by jackssrt** [comment]
This looks like a problem with your sound driver or with [playsound](https://pypi.org/project/playsound/).
Try using playsound outside of robloxnotif,
or running this script:
```python
from playsound import playsound
playsound('/path/to/a/sound/file/you/want/to/play.mp3')
```
If that doesnt work, try updating your sound card drivers
This can be done on Windows using device manager:
![Device manager search result](https://user-images.githubusercontent.com/33695699/130080087-e594ef66-3225-4432-9705-6c00a95b90ae.png)
![Instructions](https://user-images.githubusercontent.com/33695699/130081762-985f4df1-6b6e-48f2-a9a2-1e3578f77183.png)
(I've been thinking about switching over to [pygame](https://pypi.org/project/pygame/).mixer for some time now, I will need to test it though.
If nothing else works you can also try using `pygame.mixer` outside of robloxnotif)

**Comment by StevenRafft** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/61917452/130083476-e30b75d2-4f4a-41bb-b312-05c1b12a7fc3.png)
Sorry, I don't see that button, I'll try using the script you mentioned in just a second :)

**Comment by jackssrt** [comment]
> ![Screenshot_9](https://user-images.githubusercontent.com/61917452/130083476-e30b75d2-4f4a-41bb-b312-05c1b12a7fc3.png)
> Sorry, I don't see that button, I'll try using the script you mentioned in just a second :)
You have to select your audio output device to see the button, Sorry if that wasn't clear in the first comment.

**Comment by StevenRafft** [comment]
The sound played, my script:
```
playsound("C:/Users/[blank]/Desktop/robloxnotif/sounds/fav.wav")
```

**Comment by StevenRafft** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/61917452/130084082-374b825d-d7e7-485b-aa50-f1c62039d8da.png)
![Screenshot_11](https://user-images.githubusercontent.com/61917452/130084093-709b6b24-9424-4b8b-bc23-b223ea20b538.png)
![Screenshot_12](https://user-images.githubusercontent.com/61917452/130084095-c95a057a-1471-4aee-be39-2be53421122d.png)
![Screenshot_13](https://user-images.githubusercontent.com/61917452/130084099-8ff6e60e-7ec6-4485-a0e4-9568f62ab2ea.png)
All of my drivers are up-to-date.

**Comment by jackssrt** [comment]
> The sound played, my script:
> 
> ```
> playsound("C:/Users/[blank]/Desktop/robloxnotif/sounds/fav.wav")
> ```

Does it still work if you use a relative path in that script?
something like:
```python
playsound("./sounds/mysound.wav")
```

**Comment by StevenRafft** [comment]
![Screenshot_14](https://user-images.githubusercontent.com/61917452/130085670-35abfb64-04b1-4557-8178-80801a6eeee7.png)
Didn't work?

**Comment by jackssrt** [comment]
> 
> 
> ![Screenshot_14](https://user-images.githubusercontent.com/61917452/130085670-35abfb64-04b1-4557-8178-80801a6eeee7.png)
> Didn't work?

1: Run it from a .py file and not in the REPL
2: Make sure there is a there a file called `mysound.wav` under a folder called `sounds` in the same folder as the .py file

**Comment by StevenRafft** [comment]
I did that too, got the same error.

**Comment by jackssrt** [comment]
> 
> 
> I did that too, got the same error.

I'll make a new commit that changes it to use absolute paths then.

**Comment by jackssrt** [comment]
Closed by [this commit](https://github.com/jackssrt/robloxnotif/commit/493926ac8b8a9a7496522215ed64aa00e88b1b08).
