### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Minhe173** [jackssrt/robloxnotif#4]
Traceback (most recent call last):
  File "C:\Users\pog\Downloads\robloxnotif-master\robloxnotif-master\main.py", line 51, in main
    notify(config.usernames, presences[a], True)
  File "C:\Users\pog\Downloads\robloxnotif-master\robloxnotif-master\modules\notifications.py", line 64, in notify
    toast.show_toast(
TypeError: ToastNotifier.show_toast() got an unexpected keyword argument 'sound'
What's happened??? I just downloaded all packages.

**Comment by jackssrt** [comment]
I accidentally put the original win10toast in requirements.txt instead of the fork with the sound option. I'll push a commit to fix it...

**Comment by Minhe173** [comment]
Thx

**Comment by Minhe173** [comment]
C:\Users\pog>python -m pip freeze
a==1.0
about-time==3.1.1
aiohttp==3.7.4.post0
aiosignal==1.2.0
altgraph==0.17.2
antiorm==1.2.1
anyio==3.5.0
appdirs==1.4.4
argumentparser==1.2.1
asgiref==3.5.0
asttokens==2.0.5
async-generator==1.10
async-timeout==3.0.1
asyncio==3.4.3
atomicwrites==1.4.0
attrs==21.4.0
backcall==0.2.0
beautifulsoup4==4.10.0
bidict==0.21.4
bottle==0.12.19
bower==0.0.0
Brotli==1.0.9
browser-cookie3==0.13.0
bs4==0.0.1
callable==0.1.2
certifi==2021.10.8
cffi==1.15.0
cfscrape==2.1.1
chardet==3.0.4
charset-normalizer==2.0.12
choice==0.1
chromedriver==2.24.1
click==7.1.2
colorama==0.4.4
colored==1.4.3
coloredlogs==15.0.1
commonmark==0.9.1
configparser==5.2.0
controller==0.1.0
Counter==1.0.0
coverage==6.3.2
cprint==1.2.2
crayons==0.4.0
cryptocompare==0.7.5
cryptography==36.0.1
cssselect==1.1.0
curve==0.0.7
cycler==0.11.0
darr==0.5.0
DateTime==4.3
db==0.1.1
decorator==5.1.1
delete==0.3.0
Deprecated==1.2.13
dhook==0.0.1
dhooks==1.1.4
discord==1.7.3
discord-webhook==0.14.0
discord.py==1.7.3
discordwebhook==1.0.3
discum==1.4.0
Django==4.0.3
dnspython==2.2.0
dynaconf==3.1.7
easygui==0.98.2
emoji==1.6.3
ethminer==0.0.1
executing==0.8.3
exit==2020.12.3
expandvars==0.9.0
exrex==0.10.5
fade==0.0.9
fake-useragent==0.1.11
Faker==13.3.2
fancycompleter==0.9.1
File-Converter==0.1
filetype==1.0.10
fingerprint==0.1.6
flake8==4.0.1
Flask==2.0.3
fonttools==4.29.1
fore==0.1
frozenlist==1.3.0
future==0.18.2
gevent==21.12.0
gitdb==4.0.9
GitPython==3.1.27
google==3.0.0
GPUtil==1.4.0
greenlet==1.1.2
grequests==0.6.0
h11==0.13.0
h2==3.2.0
hpack==3.0.0
http3==0.6.7
httpcore==0.13.2
httplib2==0.20.4
httpx==0.18.1
humanfriendly==10.0
humanize==3.14.0
hyperframe==5.2.0
icmplib==3.0.3
idna==2.10
ImageHash==4.2.1
importlib-metadata==4.11.1
iniconfig==1.1.1
init==0.1.0
install==1.3.5
ipaddress==1.0.23
ipython==8.1.1
irc==20.0.0
itsdangerous==2.0.1
jaraco.classes==3.2.1
jaraco.collections==3.5.1
jaraco.context==4.1.1
jaraco.functools==3.5.0
jaraco.logging==3.1.0
jaraco.stream==3.0.3
jaraco.text==3.7.0
jedi==0.18.1
jeepney==0.7.1
Jinja2==3.0.3
Js2Py==0.71
jsonc-parser==1.1.5
keyboard==0.13.5
keyring==23.5.0
kiwisolver==1.3.2
konfig==1.1
ldap3==2.9.1
ldapdomaindump==0.9.3
line==0.8.2
load==2020.12.3
loads==0.3
lock==2018.3.25.2110
loguru==0.5.3
lxml==4.7.1
lz4==4.0.0
MarkupSafe==2.0.1
matplotlib==3.5.1
matplotlib-inline==0.1.3
maxminddb==2.2.0
mccabe==0.6.1
mongo==0.2.0
more-itertools==8.12.0
MouseInfo==0.1.3
multidict==6.0.2
mutagen==1.45.1
mysql-connector-python==8.0.28
netaddr==0.8.0
notify-py==0.3.3
numpy==1.22.2
outcome==1.1.0
packaging==21.3
panda==0.3.1
pandas==1.4.1
parse==1.19.0
parse-args==2.0.0
parso==0.8.3
path==16.3.0
pbkdf2==1.3
pd==0.0.4
pdbpp==0.10.3
pefile==2021.9.3
pickleshare==0.7.5
PIL-Tools==1.1.0
Pillow==9.0.1
playsound==1.3.0
pluggy==1.0.0
plyer==2.0.0
pool==0.1.2.dev0
pprintpp==0.4.0
print-function==1.0.2
progress==1.6
progressbar==2.5
prompt-toolkit==3.0.28
protobuf==3.19.4
proxy==0.0.1
proxychecker==0.0.2
proxytools==0.0.3
psutil==5.9.0
psycopg2==2.9.3
pure-eval==0.2.2
py==1.11.0
py-cpuinfo==8.0.0
pyaes==1.6.1
pyarmor==7.4.0
pyasn1==0.4.8
PyAutoGUI==0.9.53
pycodestyle==2.8.0
pycountry==22.1.10
pycountry-convert==0.7.2
pycparser==2.21
pycryptodome==3.14.1
pycryptodomex==3.14.1
pydantic==1.9.0
PyDirectInput==1.0.4
pyee==8.2.2
pyfiglet==0.7.5
pyflakes==2.4.0
pygame==2.1.2
PyGetWindow==0.0.9
PyGithub==1.55
Pygments==2.11.2
pyinstaller==4.10
pyinstaller-hooks-contrib==2022.2
pyjsparser==2.7.1
PyJWT==2.3.0
pymongo==4.0.1
PyMsgBox==1.0.9
PyNaCl==1.5.0
pyOpenSSL==22.0.0
pyparsing==3.0.7
pyperclip==1.8.2
pypiwin32==223
pyppeteer==0.2.6
pyppeteer-stealth==2.7.3
pypresence==4.2.1
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.1
PyQtWebEngine==5.15.5
PyQtWebEngine-Qt5==5.15.2
pyquery==1.4.0
pyreadline==2.1
pyreadline3==3.4.1
PyRect==0.2.0
pyrepl==0.9.0
pyroxy==0.1
PyScreeze==0.1.28
PySide2==5.15.2.1
PySocks==1.7.1
pystray==0.19.2
pytest==7.0.1
pytest-cov==3.0.0
pytest-flake8==1.0.7
pytest-mock==3.7.0
python-dateutil==2.8.2
python-dotenv==0.19.2
python-engineio==4.3.1
python-socketio==5.5.1
pytils==0.4.1
pytimeparse==1.1.8
pytube==11.0.2
pytweening==1.0.4
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.2.0
pywin32==303
pywin32-ctypes==0.2.0
PyYAML==6.0
pyzmq==22.3.0
random-username==1.0.2
rapidfuzz==2.0.0
repoze.lru==0.7
requests==2.26.0
requests-html==0.10.0
requests-mock==1.9.3
requests-toolbelt==0.9.1
rfc3986==1.5.0
roblox==2.0.0
robloxapi==4.7
rsa==4.8
scipy==1.8.0
SecretStorage==3.3.1
selenium==3.141.0
selenium-stealth==1.0.6
shiboken2==5.15.2.1
six==1.16.0
smmap==5.0.0
sniffio==1.2.0
socks==0
SocksiPy-branch==1.1
sortedcontainers==2.4.0
sound==0.1.0
SoundFile==0.10.3.post1
soupsieve==2.3.1
spark-parser==1.8.9
spotipy==2.19.0
SQLAlchemy==1.4.32
sqlparse==0.4.2
stack-data==0.2.0
style==1.1.6
tbomb==2.1.2
tempora==5.0.1
termcolor==1.1.0
terminal==0.4.0
threadpool==1.3.2
tiktokpy==0.8.9
timeout==0.1.2
tomli==2.0.1
tools==0.1.9
tqdm==4.63.0
traitlets==5.1.1
trio==0.19.0
trio-websocket==0.9.2
typer==0.3.2
typing==3.7.4.3
typing_extensions==4.1.1
tzdata==2021.5
tzlocal==4.1
ua-parser==0.10.0
uc==2.2.1
ujson==5.1.0
uncompyle6==3.8.0
undetected-chromedriver==3.1.3
Unidecode==1.3.2
urllib3==1.26.8
user-agent==0.1.10
varint==1.0.2
w3lib==1.22.0
waitress==2.0.0
walk==0.3.5
wcwidth==0.2.5
webdriver-manager==3.5.3
WebOb==1.8.7
websocket-client==0.59.0
websockets==9.1
WebTest==3.0.0
Werkzeug==2.0.3
wget==3.2
win10toast==0.9
win10toast-withsound==0.9
win32-setctime==1.1.0
window==0.0.3
wmctrl==0.4
wrapt==1.13.3
ws4py==0.5.1
WSGIProxy2==0.5.1
wsproto==1.0.0
xdis==6.0.3
xss-utils==0.4.0
yarl==1.7.2
youtube-dl==2021.12.17
youtube-downloader==0.6.0
zipp==3.7.0
zope.event==4.5.0
zope.interface==5.4.0

**Comment by Minhe173** [comment]
oh no its error again

**Comment by Minhe173** [comment]
Error 259 for command:
        play "C:\Users\pog\Downloads\robloxnotif-master\robloxnotif-master\sounds\robloxnotif.wav" wait
    The driver cannot recognize the specified command parameter.
[10:02:05]: [ERROR] [FATAL] PlaysoundException
    Error 259 for command:
        play "C:\Users\pog\Downloads\robloxnotif-master\robloxnotif-master\sounds\robloxnotif.wav" wait
    The driver cannot recognize the specified command parameter.
Unexpected error, Can't continue running.
Check error.log for a traceback.
Exception in thread Thread-2 (_show_toast):
Traceback (most recent call last):
  File "C:\Users\pog\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\pog\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pog\AppData\Local\Programs\Python\Python310\lib\site-packages\win10toast\__init__.py", line 84, in _show_toast
    self.hwnd = CreateWindow(self.classAtom, "Taskbar", style,
AttributeError: 'ToastNotifier' object has no attribute 'classAtom'

**Comment by jackssrt** [comment]
Try updating your sound driver for the first error, and for the second one just restart robloxnotif.

**Comment by Minhe173** [comment]
umm its fine, i can hear audio but then it shows this error

**Comment by Minhe173** [comment]
it worked now:D
